export type ErrorCodes =
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'DEPENDENCY_FAILURE'
  | 'TIMEOUT'
  | 'INTERNAL_ERROR';

export const HTTP_STATUS: Record<ErrorCodes, number> = {
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  DEPENDENCY_FAILURE: 502,
  TIMEOUT: 504,
  INTERNAL_ERROR: 500,
};
